cors:
  originPatterns: https://www.udemy.com,http://localhost:8080
spring:
  application:
    name: gerenciamento-hostpitalar
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    jwt:
      secret-key: 53cr3t
      expire-length: 3600000
springdoc:
  override-with-generic-response: false

